export default {
  NUXT_SERVER_INIT: 'nuxtServerInit',
  SET_CONTENTS: 'SET_CONTENTS',
  FETCH_MARKDOWN: 'FETCH_MARKDOWN',
  SET_MARKDOWN: 'SET_MARKDOWN',
  SET_THEME: 'SET_THEME',
  SET_FILTER: 'SET_FILTER',
  RESET_FILTER: 'RESET_FILTER',
  SET_VISIBILITY: 'SET_VISIBILITY',
  FETCH_CONTENT: 'FETCH_CONTENT',
  SET_RESPONSE: 'SET_RESPONSE',
  SET_HEADING: 'SET_HEADING',
}
