export default {
  FETCH_MARKDOWN: 'FETCH_MARKDOWN',
  SET_MARKDOWN: 'SET_MARKDOWN',
  SET_THEME: 'SET_THEME',
  SET_FILTER: 'SET_FILTER',
  RESET_FILTER: 'RESET_FILTER',
  SET_VISIBILITY: 'SET_VISIBILITY',
}
