export default {
  NUXT_SERVER_INIT: 'nuxtServerInit',
  WATCH_MARKDOWN: 'WATCH_MARKDOWN',
  SET_THEME: 'SET_THEME',
  SET_FILTER: 'SET_FILTER',
  RESET_FILTER: 'RESET_FILTER',
  SET_VISIBILITY: 'SET_VISIBILITY',
  FETCH_CONTENT: 'FETCH_CONTENT',
  SET_RESPONSE: 'SET_RESPONSE',
  FETCH_CONTENTS_LIST: 'FETCH_CONTENTS_LIST',
  SET_CONTENTS_LIST: 'SET_CONTENTS_LIST',
  FETCH_HEADING: 'FETCH_HEADING',
  SET_HEADING: 'SET_HEADING',
}
